services:
  - type: web
    name: twitter-flask
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: TWITTER_CONSUMER_KEY
        value: your_consumer_key
      - key: TWITTER_CONSUMER_SECRET
        value: your_consumer_secret
      - key: TWITTER_ACCESS_TOKEN
        value: your_access_token
      - key: TWITTER_ACCESS_SECRET
        value: your_access_secret
